nursery_subjects = [
    "MATHEMATICS",
    "ENGLISH LANGUAGE",
    "PHONICS",
    "HANDWRITING",
    "SOCIAL HABIT",
    "SECURITY EDUCATION",
    "SCIENCE SKILLLS",
    "PHYSICAL AND HEALTH EDUCATION",
    "FOOD AND NUTRITION",
    "WATER AND ENVIRONMENTAL SANITATION",
    "RELIGIOUS STUDIES (C.R.S)",
    "VERBAL REASONING",
    "QUANTITATIVE REASONING",
    "RHYMES",
    "SENSORIAL"
]
